-- ============================================
-- GENERATE DUMMY DONASI (VERSI SEDERHANA)
-- Script untuk membuat data dummy donasi yang terkait dengan donatur
-- Versi ini menggunakan INSERT langsung tanpa stored procedure
-- 
-- REKOMENDASI: Gunakan versi ini jika versi stored procedure bermasalah
-- Cara penggunaan:
-- 1. Pastikan sudah ada donatur (jalankan generate_dummy_donatur_500.sql terlebih dahulu)
-- 2. Copy semua isi file ini
-- 3. Paste di phpMyAdmin atau MySQL client
-- 4. Jalankan
-- 
-- Script ini akan generate sekitar 1000 donasi (500 + 300 + 200)
-- Untuk mengubah jumlah, edit angka LIMIT di setiap INSERT statement
-- ============================================

-- Hapus data dummy sebelumnya (opsional, comment jika tidak ingin menghapus)
-- DELETE FROM csr_donations WHERE nama_donatur LIKE '%dummy%' OR keterangan LIKE '%Dummy%';

-- Ambil semua donatur aktif
SET @donatur_count = (SELECT COUNT(*) FROM donatur WHERE status = 'active');

-- Jika tidak ada donatur, tampilkan pesan
SELECT IF(@donatur_count = 0, 
    'Tidak ada donatur aktif. Silakan generate donatur terlebih dahulu.',
    CONCAT('Akan generate donasi untuk ', @donatur_count, ' donatur aktif')
) AS info;

-- Generate donasi untuk setiap donatur (sekitar 2-5 donasi per donatur)
INSERT INTO `csr_donations` (
    `donatur_id`, 
    `nama_donatur`, 
    `jumlah`, 
    `tanggal`, 
    `metode_pembayaran`, 
    `kategori`, 
    `program`, 
    `status`, 
    `keterangan`, 
    `created_at`
)
SELECT 
    d.id AS donatur_id,
    d.nama AS nama_donatur,
    -- Generate jumlah donasi (antara 10.000 - 50.000.000)
    CASE 
        WHEN (d.id * 7) % 10 < 3 THEN FLOOR(10000 + (d.id * 123) % 990000) -- 10rb - 1jt (30%)
        WHEN (d.id * 7) % 10 < 6 THEN FLOOR(1000000 + (d.id * 456) % 9000000) -- 1jt - 10jt (30%)
        WHEN (d.id * 7) % 10 < 8 THEN FLOOR(10000000 + (d.id * 789) % 40000000) -- 10jt - 50jt (25%)
        ELSE FLOOR(50000000 + (d.id * 321) % 50000000) -- 50jt - 100jt (15%)
    END AS jumlah,
    -- Generate tanggal (dalam 2 tahun terakhir)
    DATE_SUB(CURDATE(), INTERVAL (d.id * 13) % 730 DAY) AS tanggal,
    -- Generate metode pembayaran
    CASE (d.id * 3) % 5
        WHEN 0 THEN 'tunai'
        WHEN 1 THEN 'transfer'
        WHEN 2 THEN 'qris'
        WHEN 3 THEN 'kartu'
        ELSE 'lainnya'
    END AS metode_pembayaran,
    -- Generate kategori
    CASE (d.id * 5) % 6
        WHEN 0 THEN 'zakat'
        WHEN 1 THEN 'infaq'
        WHEN 2 THEN 'sedekah'
        WHEN 3 THEN 'donasi_umum'
        WHEN 4 THEN 'csr'
        ELSE 'wakaf'
    END AS kategori,
    -- Generate program (60% punya program)
    CASE 
        WHEN (d.id * 11) % 10 < 6 THEN 
            CASE (d.id * 7) % 10
                WHEN 0 THEN 'Program Pendidikan Anak Yatim'
                WHEN 1 THEN 'Program Bantuan Pangan'
                WHEN 2 THEN 'Program Kesehatan Masyarakat'
                WHEN 3 THEN 'Program Bencana Alam'
                WHEN 4 THEN 'Program Infrastruktur Desa'
                WHEN 5 THEN 'Program Beasiswa'
                WHEN 6 THEN 'Program Kesejahteraan Lansia'
                WHEN 7 THEN 'Program Lingkungan Hidup'
                WHEN 8 THEN 'Program Ekonomi Kreatif'
                ELSE 'Program Dakwah'
            END
        ELSE NULL
    END AS program,
    -- Generate status (80% verified, 15% pending, 5% rejected)
    CASE 
        WHEN (d.id * 17) % 100 < 80 THEN 'verified'
        WHEN (d.id * 17) % 100 < 95 THEN 'pending'
        ELSE 'rejected'
    END AS status,
    CONCAT('Dummy donasi untuk ', d.nama, ' - Generated by script') AS keterangan,
    DATE_SUB(NOW(), INTERVAL (d.id * 19) % 730 DAY) AS created_at
FROM donatur d
WHERE d.status = 'active'
LIMIT 500;

-- Generate donasi kedua untuk beberapa donatur (untuk variasi)
INSERT INTO `csr_donations` (
    `donatur_id`, 
    `nama_donatur`, 
    `jumlah`, 
    `tanggal`, 
    `metode_pembayaran`, 
    `kategori`, 
    `program`, 
    `status`, 
    `keterangan`, 
    `created_at`
)
SELECT 
    d.id AS donatur_id,
    d.nama AS nama_donatur,
    CASE 
        WHEN (d.id * 23) % 10 < 3 THEN FLOOR(10000 + (d.id * 234) % 990000)
        WHEN (d.id * 23) % 10 < 6 THEN FLOOR(1000000 + (d.id * 567) % 9000000)
        WHEN (d.id * 23) % 10 < 8 THEN FLOOR(10000000 + (d.id * 890) % 40000000)
        ELSE FLOOR(50000000 + (d.id * 432) % 50000000)
    END AS jumlah,
    DATE_SUB(CURDATE(), INTERVAL (d.id * 29) % 730 DAY) AS tanggal,
    CASE (d.id * 7) % 5
        WHEN 0 THEN 'tunai'
        WHEN 1 THEN 'transfer'
        WHEN 2 THEN 'qris'
        WHEN 3 THEN 'kartu'
        ELSE 'lainnya'
    END AS metode_pembayaran,
    CASE (d.id * 11) % 6
        WHEN 0 THEN 'zakat'
        WHEN 1 THEN 'infaq'
        WHEN 2 THEN 'sedekah'
        WHEN 3 THEN 'donasi_umum'
        WHEN 4 THEN 'csr'
        ELSE 'wakaf'
    END AS kategori,
    CASE 
        WHEN (d.id * 13) % 10 < 6 THEN 
            CASE (d.id * 19) % 10
                WHEN 0 THEN 'Program Pendidikan Anak Yatim'
                WHEN 1 THEN 'Program Bantuan Pangan'
                WHEN 2 THEN 'Program Kesehatan Masyarakat'
                WHEN 3 THEN 'Program Bencana Alam'
                WHEN 4 THEN 'Program Infrastruktur Desa'
                WHEN 5 THEN 'Program Beasiswa'
                WHEN 6 THEN 'Program Kesejahteraan Lansia'
                WHEN 7 THEN 'Program Lingkungan Hidup'
                WHEN 8 THEN 'Program Ekonomi Kreatif'
                ELSE 'Program Dakwah'
            END
        ELSE NULL
    END AS program,
    CASE 
        WHEN (d.id * 31) % 100 < 80 THEN 'verified'
        WHEN (d.id * 31) % 100 < 95 THEN 'pending'
        ELSE 'rejected'
    END AS status,
    CONCAT('Dummy donasi kedua untuk ', d.nama, ' - Generated by script') AS keterangan,
    DATE_SUB(NOW(), INTERVAL (d.id * 37) % 730 DAY) AS created_at
FROM donatur d
WHERE d.status = 'active'
LIMIT 300;

-- Generate donasi ketiga untuk beberapa donatur (untuk variasi lebih banyak)
INSERT INTO `csr_donations` (
    `donatur_id`, 
    `nama_donatur`, 
    `jumlah`, 
    `tanggal`, 
    `metode_pembayaran`, 
    `kategori`, 
    `program`, 
    `status`, 
    `keterangan`, 
    `created_at`
)
SELECT 
    d.id AS donatur_id,
    d.nama AS nama_donatur,
    CASE 
        WHEN (d.id * 41) % 10 < 3 THEN FLOOR(10000 + (d.id * 345) % 990000)
        WHEN (d.id * 41) % 10 < 6 THEN FLOOR(1000000 + (d.id * 678) % 9000000)
        WHEN (d.id * 41) % 10 < 8 THEN FLOOR(10000000 + (d.id * 901) % 40000000)
        ELSE FLOOR(50000000 + (d.id * 543) % 50000000)
    END AS jumlah,
    DATE_SUB(CURDATE(), INTERVAL (d.id * 43) % 730 DAY) AS tanggal,
    CASE (d.id * 13) % 5
        WHEN 0 THEN 'tunai'
        WHEN 1 THEN 'transfer'
        WHEN 2 THEN 'qris'
        WHEN 3 THEN 'kartu'
        ELSE 'lainnya'
    END AS metode_pembayaran,
    CASE (d.id * 17) % 6
        WHEN 0 THEN 'zakat'
        WHEN 1 THEN 'infaq'
        WHEN 2 THEN 'sedekah'
        WHEN 3 THEN 'donasi_umum'
        WHEN 4 THEN 'csr'
        ELSE 'wakaf'
    END AS kategori,
    CASE 
        WHEN (d.id * 47) % 10 < 6 THEN 
            CASE (d.id * 23) % 10
                WHEN 0 THEN 'Program Pendidikan Anak Yatim'
                WHEN 1 THEN 'Program Bantuan Pangan'
                WHEN 2 THEN 'Program Kesehatan Masyarakat'
                WHEN 3 THEN 'Program Bencana Alam'
                WHEN 4 THEN 'Program Infrastruktur Desa'
                WHEN 5 THEN 'Program Beasiswa'
                WHEN 6 THEN 'Program Kesejahteraan Lansia'
                WHEN 7 THEN 'Program Lingkungan Hidup'
                WHEN 8 THEN 'Program Ekonomi Kreatif'
                ELSE 'Program Dakwah'
            END
        ELSE NULL
    END AS program,
    CASE 
        WHEN (d.id * 53) % 100 < 80 THEN 'verified'
        WHEN (d.id * 53) % 100 < 95 THEN 'pending'
        ELSE 'rejected'
    END AS status,
    CONCAT('Dummy donasi ketiga untuk ', d.nama, ' - Generated by script') AS keterangan,
    DATE_SUB(NOW(), INTERVAL (d.id * 59) % 730 DAY) AS created_at
FROM donatur d
WHERE d.status = 'active'
LIMIT 200;

-- ============================================
-- VERIFIKASI DATA
-- ============================================
SELECT 
    COUNT(*) AS total_donasi,
    SUM(jumlah) AS total_nominal,
    COUNT(CASE WHEN status = 'verified' THEN 1 END) AS verified,
    COUNT(CASE WHEN status = 'pending' THEN 1 END) AS pending,
    COUNT(CASE WHEN status = 'rejected' THEN 1 END) AS rejected,
    COUNT(DISTINCT donatur_id) AS total_donatur_berdonasi
FROM csr_donations;

-- Top 10 donatur berdasarkan total donasi
SELECT 
    d.nama,
    COUNT(ds.id) AS jumlah_donasi,
    SUM(ds.jumlah) AS total_donasi
FROM donatur d
LEFT JOIN csr_donations ds ON d.id = ds.donatur_id
GROUP BY d.id, d.nama
ORDER BY total_donasi DESC
LIMIT 10;

-- ============================================
-- SELESAI
-- Total donasi yang di-generate: sekitar 1000 donasi
-- ============================================

